[package]
name = "todo-db"
version = "0.1.0"
authors = ["Takamichi Tsutsumi <1220t.takamichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rusqlite = "0.20.0"
